### ISSUE TITLE
Remove old notebooks and data from JupyterLab

### ISSUE THREAD

**Issue by fmcclean** [dafnifacility/user-feedback#39]
The housing notebook, 5G notebook, and LADs data still appear in new instances.

**Comment by BethanPerkins** [comment]
Thanks for this Fergus - created ticket [CORE-1400](https://jira.dafni.rl.ac.uk/browse/CORE-1400) (DAFNI Internal) for this

**Comment by JusteRaimbault** [comment]
I have the same issue - what is strange is that notebooks and data persistent are only the ones from example models I ran (5G and housing models), but not from my own workflows; they have their separate jupyter workflow (which is I guess the expected behavior).
A related suggestion, could we add the option to copy/reuse a previous jupyter workspace to reuse scripts for example?

**Comment by fmcclean** [comment]
> A related suggestion, could we add the option to copy/reuse a previous jupyter workspace to reuse scripts for example?

An interim solution to this would be to include a notebook file from the model image in the visualisation step. It would then get included in the data catalogue entry though so not ideal.

**Comment by BethanPerkins** [comment]
Ticket resolved in DAFNI release v1.11.0 (10 November 2020). Closing this issue.

We'll be adding in the option for users to 'save' their jupyter notebooks as visualisation templates soon as part of our new visualisation infrastructure.
