### ISSUE TITLE
Handle publish before upload complete

### ISSUE THREAD

**Issue by fmcclean** [dafnifacility/user-feedback#54]
Clicking the publish button before data is finished uploading currently leads to the error "Commit Dataset Error: No Files in temporary area to commit". Ideally what should happen when the publish button is clicked is the app should wait until the data uploads and then publish it. The problem with how it is now is that you have to sit and wait until a dataset uploads, rather than being able to leave it to complete on its own.

**Comment by roseDickinson** [comment]
Hi Fergus,

We have a task in our backlog ([CORE-1061](https://jira.dafni.rl.ac.uk/browse/CORE-1061) internal link) that covers moving data upload to a single step rather than the current 2 step process. This task would involve removing the initial "upload" button that currently exists and changing the publish button to trigger both the upload of the data (with progress bars) and then the publishing of the metadata. 

Does this sound like a good solution to you?

**Comment by fmcclean** [comment]
Sounds good to me (linked to #32)

**Comment by BethanPerkins** [comment]
CORE-1061 released in v1.15. Data upload is now a single step. Closing ticket as done.
