### ISSUE TITLE
Show most recent version first

### ISSUE THREAD

**Issue by fmcclean** [dafnifacility/user-feedback#63]
Versions are currently sorted in ascending date order, please could this be descending instead?

**Comment by BethanPerkins** [comment]
To check understanding, is this a request to re-order the contents of the model/dataset version history list, so that the latest version is at the bottom, rather than the top?

If so, then the problem with this approach is that once you have more than 5 versions of a model/dataset, then the most recent version will drop out of the first page of the version history dialogue. We've gone with a standard 'most recent floats to the top' approach to avoid that.

**Comment by BethanPerkins** [comment]
Hi Fergus - could you give us a screenshot of where this is happening please?

**Comment by fmcclean** [comment]
![image](https://user-images.githubusercontent.com/17356802/109302015-a6f88400-7830-11eb-98bb-1e8a3dd8795c.png)

**Comment by BethanPerkins** [comment]
Thanks very much. This is inconsistent with some other models - definitely a bug. Captured in [CORE-1738](https://jira.dafni.rl.ac.uk/browse/CORE-1738)

**Comment by BethanPerkins** [comment]
This has been fixed in Release 2.1.0
