### ISSUE TITLE
Add ability to create step not at end

### ISSUE THREAD

**Issue by fmcclean** [dafnifacility/user-feedback#76]
I am trying to add a step at the start of a workflow but this is not possible at the moment. It would be helpful to be able to create steps either at the start or between any other two steps because otherwise the entire workflow needs to be recreated.

**Comment by fmcclean** [comment]
Linked to this is the ability to delete and reposition steps. I can add these as new issues if that would be more convenient?

**Comment by BethanPerkins** [comment]
I think the additional points are captured appropriately here - no need to make other issues at the moment.

**Comment by fmcclean** [comment]
These features will become more essential requirements for longer workflows - it's not practical to recreate 5+ steps to remove or add 1.

**Comment by roseDickinson** [comment]
Unfortunately due to the way the UI for Workflows is currently written and the tool that is currently used behind the scenes this is a much larger change than it should be as we would need to refactor and rewrite a lot of the code that is currently there, this also affects deletion and repositioning steps. We are planning on moving to a different tool for Workflow creation, which will hopefully be a drag and drop tool allowing, creation of steps anywhere along a workflow, removal of steps and repositioning. This would also be a large change and I'm not sure where we are on the current priority for that move.

**Comment by BethanPerkins** [comment]
Making a note to raise this at the next prioritisation meeting. If you could keep us up to date on how it's impacting your work Fergus, that would be helpful.

**Comment by tg137** [comment]
This is covered by our epic associated with changing the framework behind the workflow creation page. We will move to something more dynamic which will allow things like step deletion and creation of steps in the middle of the workflow. https://jira.dafni.rl.ac.uk/browse/CORE-2155

**Comment by roseDickinson** [comment]
As of v4.0.0, the new workflow builder allows for this drag + drop creation of steps anywhere and repositioning those steps to wherever you would like in the workflow.
