### ISSUE TITLE
Delay in workflow execution popup

### ISSUE THREAD

**Issue by fmcclean** [dafnifacility/user-feedback#88]
After clicking `Execute`, there can be a delay of 10+ seconds before the popup is shown saying that the workflow execution has started. This leaves the user uncertain as to whether the button has been clicked properly and may result in the button being clicked again.

It's a minor issue but a better user experience might be to show a popup instantly after clicking the `Execute` button. This popup could let the user know that the request has been sent and be updated when the workflow starts executing.

**Comment by tg137** [comment]
Thanks Fergus.

I have reservations about popping up immediately in case something goes wrong with the request. I'd advocate for a loading spinner of some description that freezes the screen so that the user is aware something is happening and such that they cannot press anything else at the time. 

What do you think?

Captured internally at https://jira.dafni.rl.ac.uk/browse/CORE-1991

**Comment by fmcclean** [comment]
That's basically what I was thinking so sounds good to me.

**Comment by tg137** [comment]
This was fixed in version 3.0.0
